Upped movement speed and allowed owl through new tileset on Treetops 4
Cosmic-Cryptid-Games/GrowingDepths pull request #123
Opened 2019-10-17 17:31 UTC by modelarious

close #59 
close #122
close #78

2019-10-19 02:37 UTC, rye-f requested changes
When I played, the wind still ran on Treetops 5

2019-10-19 18:27 UTC, modelarious commented
Should be fixed now, thanks for pointing that out

2019-10-21 23:06 UTC, reillykeele approved these changes

2019-10-21 23:54 UTC, rye-f approved these changes

2019-10-21 23:54 UTC, merged