Imported Avery's Tileset to the Maps
Cosmic-Cryptid-Games/GrowingDepths pull request #135
Opened 2019-10-21 22:23 UTC by mfournier98

2019-10-21 22:34 UTC, modelarious requested changes
The tilesets are looking good, but it looks like some of the collision has been lost (for example, the tree texture in Treetops 6 should have collision with the player), or the texture has been replaced with something that doesn't reflect the original (like Treetops 7, there is a death zone of "66" tiles near the start that looks identical to the safe blocks)

2019-10-21 22:46 UTC, reillykeele approved these changes

2019-10-21 22:48 UTC, reillykeele approved these changes

2019-10-22 00:04 UTC, modelarious commented
Closed this as I messed up the merge. opened #140

2019-10-22 00:04 UTC, closed without merging