Fixed the issue with the direction
Cosmic-Cryptid-Games/GrowingDepths pull request #240
Opened 2019-10-31 23:37 UTC by mfournier98

2019-10-31 23:38 UTC, mfournier98 commented
close #238

2019-11-01 00:55 UTC, modelarious requested changes
This works well for when the player transitions between screens, but when the player first spawns into the game they are facing left but will dash right if that's the first button the player presses

2019-11-01 01:15 UTC, modelarious commented
Nevermind, I now see that it works on spawn, but only if you spawn in the Light forest 1. Sorry about that!

2019-11-01 01:15 UTC, modelarious approved these changes

2019-11-01 01:15 UTC, merged